hetznercloud/hcloud-go

hcloud/schema/server.go
hcloud/server.go
hcloud/server_test.go

Implement rebuilding a server

---

hcloud/schema/server.go
hcloud/server.go
hcloud/server_test.go

Implement attaching and detaching ISOs

---

hcloud/schema/server.go
hcloud/server.go
hcloud/server_test.go

Implement enabling and disabling backup

---

hcloud/schema/server.go
hcloud/server.go
hcloud/server_test.go

Implement updating servers

---

hcloud/image.go
hcloud/image_test.go
hcloud/schema/image.go

Implement updating an image

---

hcloud/schema/server.go
hcloud/server.go
hcloud/server_test.go

Implement changing a server's type

---

hcloud/action.go
hcloud/action_test.go
hcloud/schema/action.go

Implement listing actions

---

hcloud/schema/ssh_key.go
hcloud/ssh_key.go
hcloud/ssh_key_test.go

Implement updating a SSH key

---

hcloud/floating_ip.go
hcloud/floating_ip_test.go
hcloud/schema/floating_ip.go

Implement updating a Floating IP

---

hcloud/client.go
hcloud/pricing.go
hcloud/pricing_test.go
hcloud/schema.go
hcloud/schema/pricing.go
hcloud/schema/server_type.go
hcloud/schema_test.go
hcloud/server_type.go

Implement retrieving pricing information

---

hcloud/schema/server.go
hcloud/server.go
hcloud/server_test.go

Implement changing DNS ptr for a server IP

---

hcloud/floating_ip.go
hcloud/floating_ip_test.go
hcloud/schema/floating_ip.go

Implement changing DNS ptr of a Floating IP

---

hcloud/pricing.go
hcloud/schema.go
hcloud/schema/pricing.go
hcloud/schema_test.go

Traffic is billed per-TB

---

hcloud/schema.go
hcloud/schema/server.go
hcloud/schema_test.go
hcloud/server.go

Add Image property to server

---

hcloud/CHANGES.md
hcloud/client.go
hcloud/client_test.go
hcloud/error.go

Use correct error code for rate limit error

---

CHANGES.md
hcloud/client.go

Close response body

---

hcloud/hcloud_test.go

This PR includes a new example, so that godoc will recognize it and renders it correctly. 
Of course this unit test will fail, but per default it won't be executed, so everything should be fine. Maybe a good idea could be to extend it with some more functionality.

Provide a godoc conform example

---

CHANGES.md
hcloud/floating_ip.go
hcloud/floating_ip_test.go
hcloud/helper.go
hcloud/image.go
hcloud/image_test.go
hcloud/schema.go
hcloud/schema/floating_ip.go
hcloud/schema/image.go
hcloud/schema/server.go
hcloud/schema_test.go
hcloud/server.go
hcloud/server_test.go

Add ChangeProtection methods to clients

---

hcloud/action.go
hcloud/action_test.go

This PR aims to make it possible to reduce the number of action pollings.

add method for making the polling timeout configurable

---

CHANGES.md
hcloud/action.go
hcloud/client.go

Add new "WithPollInterval"-Option and remove "WatchProgressInterval" Method

---

CHANGES.md
hcloud/client.go
hcloud/client_test.go

Allows us to gather better statistics on which integrations are popular.

Allow to set application name/version for user agent

---

CHANGES.md
hcloud/action.go
hcloud/action_test.go
hcloud/client.go
hcloud/datacenter.go
hcloud/datacenter_test.go
hcloud/floating_ip.go
hcloud/image.go
hcloud/image_test.go
hcloud/iso.go
hcloud/location.go
hcloud/location_test.go
hcloud/server.go
hcloud/server_test.go
hcloud/server_type.go
hcloud/ssh_key.go
hcloud/ssh_key_test.go
hcloud/volume.go

Refactor all GetByName-Methods to use the new ListOpts parameters and the List function internally, no API change!
Closes #106

Add all available parameters to the specific ListOpts struct

---

CHANGES.md
hcloud/schema.go
hcloud/schema/volume.go
hcloud/schema_test.go
hcloud/volume.go
hcloud/volume_test.go

Add Volume Status to Volume Struct

---

CHANGES.md
hcloud/schema/server.go
hcloud/server.go
hcloud/server_test.go

Add API for requesting a WebSocket VNC console
See also: #113

Add API for requesting a VNC console

---

CHANGES.md
hcloud/load_balancer.go
hcloud/schema.go
hcloud/schema/load_balancer.go
hcloud/schema_test.go

Add `IncludedTraffic`, `OutgoingTraffic` and `IngoingTraffic` fields to `LoadBalancer`

LB Traffic fields

---

CHANGES.md
hcloud/load_balancer.go
hcloud/load_balancer_test.go
hcloud/schema.go
hcloud/schema/load_balancer.go
hcloud/schema/server.go
hcloud/schema_test.go
hcloud/server.go
hcloud/server_test.go

Expose metrics data for Hetzner Cloud Servers and Load Balancers.
Closes GH-94

Expose metrics data

---

.github/workflows/ci.yml
.github/workflows/golangci-lint.yml
.gitlab-ci.yml
.golangci.yaml
hcloud/action.go
hcloud/action_test.go
hcloud/certificate.go
hcloud/certificate_test.go
hcloud/client.go
hcloud/client_test.go
hcloud/datacenter.go
hcloud/floating_ip.go
hcloud/floating_ip_test.go
hcloud/image.go
hcloud/image_test.go
hcloud/iso.go
hcloud/load_balancer.go
hcloud/load_balancer_test.go
hcloud/load_balancer_type.go
hcloud/location.go
hcloud/network.go
hcloud/network_test.go
hcloud/schema.go
hcloud/schema/error.go
hcloud/schema_test.go
hcloud/server.go
hcloud/server_test.go
hcloud/server_type.go
hcloud/ssh_key.go
hcloud/volume.go

Add golangci-lint and fix issues

---

.github/workflows/ci.yml
.gitlab-ci.yml
go.mod

Test hcloud-go on go 1.16

---

hcloud/pricing.go
hcloud/schema.go
hcloud/schema/pricing.go
hcloud/schema_test.go

Add missing Volume Pricing Information

---

go.mod
go.sum
hcloud/action.go
hcloud/action_test.go
hcloud/client.go
hcloud/error.go
hcloud/firewall.go
hcloud/firewall_test.go
hcloud/schema.go
hcloud/schema/firewall.go
hcloud/schema/server.go
hcloud/schema_test.go
hcloud/server.go
hcloud/server_test.go

Add support for Firewalls

---

hcloud/firewall.go
hcloud/firewall_test.go
hcloud/schema.go
hcloud/schema/firewall.go
hcloud/schema_test.go

Add Firewall Resource Label Selector

---

hcloud/hcloud.go
hcloud/schema/firewall.go

Fix Labelselector causes a validation error

---

hcloud/firewall.go

Add support for firewall protocols ESP and GRE

---

hcloud/image.go

Add support for app images

---

hcloud/pricing.go
hcloud/schema.go
hcloud/schema/pricing.go
hcloud/schema_test.go

Add new Floating IP Pricing structure

---

.github/workflows/ci.yml
.github/workflows/golangci-lint.yml
.github/workflows/release.yml
.gitlab-ci.yml
go.mod
go.sum

Test on/with go 1.17

---

hcloud/load_balancer.go
hcloud/load_balancer_test.go
hcloud/schema.go
hcloud/schema/load_balancer.go
hcloud/schema_test.go

Add support for Load Balancer DNS PTRs

---

hcloud/metadata/client.go
hcloud/metadata/client_test.go

Add Metadata Client

---

hcloud/network.go

Add us-east network zone

---

hcloud/server.go

Remove ServerRescueTypeFreeBSD64

---

.github/workflows/ci.yml
.github/workflows/release.yml
hcloud/client.go
hcloud/client_test.go
hcloud/metadata/client.go

Drop support for Go < 1.17 and add official tests on go 1.19

---

.golangci.yaml
hcloud/certificate.go
hcloud/client.go
hcloud/error.go
hcloud/firewall_test.go
hcloud/floating_ip.go
hcloud/internal/instrumentation/metrics.go
hcloud/iso.go
hcloud/metadata/client.go
hcloud/placement_group.go
hcloud/placement_group_test.go
hcloud/pricing.go
hcloud/primary_ip.go
hcloud/primary_ip_test.go
hcloud/rdns.go
hcloud/schema/pricing.go
hcloud/schema/primary_ip.go
hcloud/server_test.go

Replace deprecated linters with suggested alternatives and add some new ones (gci, godot).

chore: update golangci-lint settings

---

renovate.json5

chore: fix syntax error in renovate config

---

.github/workflows/release-please.yml

Workaround for https://github.com/google-github-actions/release-please-action/issues/913
Fixes https://github.com/hetznercloud/hcloud-go/issues/361

ci: include release-please target-branch

---

hcloud/schema/primary_ip.go
hcloud/schema_gen.go
hcloud/zz_schema.go

See https://github.com/hetznercloud/cli/issues/701

fix: primary ip assignee id not mapped to nil

---

.github/workflows/golangci-lint.yml
.golangci.yaml
hcloud/schema.go

- Update the golangci-lint workflows actions to latest version
- Ignore some linting errors

test: fix golangci-lint

---

hcloud/action_waiter.go

Filter out nil actions, to help users of the function.

feat: filter out nil actions in action waiter

---

hcloud/exp/kit/envutils/env.go
hcloud/exp/kit/envutils/env_test.go

Add a function to read value from the environment or from a file.

feat(exp): add envutils package

---

hcloud/client_test.go

Missing test for the jitter code.

test: add test to exponential backoff with jitter

---

.gitlab-ci.yml

- Only run on feature branches
- Use shared cache
- Update jobs to latest best practices

ci: update gitlab ci

---

hcloud/internal/instrumentation/metrics.go

This improves the performances a bit.

refactor: move regexp compilation outside function

---

hcloud/pricing.go
hcloud/zz_schema.go

Expose currency information from the pricing endpoint. Needed to know the users currency for storage box pricing.

feat: expose account currency information

---

hcloud/schema.go
hcloud/schema/storage_box_snapshot.go
hcloud/schema_gen.go
hcloud/storage_box_snapshot.go
hcloud/storage_box_snapshot_test.go
hcloud/zz_schema.go

Adds support for Storage Box snapshots.
API Reference: https://docs.hetzner.cloud/reference/hetzner#snapshots

feat: Storage Box snapshots
