- hcloud/server.go
- hcloud/server_test.go
v1.0.0 is already tagged, but only used by our CLI, so it’s save to change it and re-tag v1.0.0.
> Update ServerCreateOpts to use pointers

- CHANGES.md
- hcloud/action.go
- hcloud/action_test.go
- hcloud/error.go
> Make old ratelimit error code work as expected

- CHANGES.md
- hcloud/error.go
This PR aims to fix #103. 
At the moment we have 12 error codes, but only five are available in the hcloud-go as constant.
When this PR is merged, it allows developers to do something like:
```go
action, _, err := client.Volume.Detach(ctx, volume)
if err != nil {
if hcloud.IsError(err, hcloud.ErrorLocked) {
// retry
}
}
``` 	
instead of
```go
action, _, err := client.Volume.Detach(ctx, volume)
if err != nil {
if hcloud.IsError(err, "locked") {
// retry
}
}
```
> Add all available error codes as constant

- CHANGES.md
- hcloud/action.go
- hcloud/action_test.go
Return the error from GetByID(), not ctx.Err() (which is nil).
Closes #108.
> Fix WatchProgress() error handling

- CHANGES.md
- hcloud/client.go
This adds a basic debug mode to the client which allows users to debug the whole request and the response. We simply "print" everything including the Headers of Request and Response.
The format was just a draft, we can of course change it.
Sample:
```
------- HCLOUD_GO_DEBUG -------
Request: GET - https://api.hetzner.cloud/v1/locations?page=1&per_page=50
Request Headers: http.Header{"Authorization":[]string{"Bearer THIS_IS_THE_TOKEN"}, "User-Agent":[]string{"hcloud-cli/was not built properly hcloud-go/1.14.0"}}
Request Body: %!s(<nil>)
Response Status Code: 200
Response Headers: http.Header{"Content-Type":[]string{"application/json"}, "Date":[]string{"Thu, 18 Jul 2019 08:47:12 GMT"}, "Link":[]string{"<https://api.hetzner.cloud/v1/locations?page=1&per_page=50>; rel=last"}, …
```
> Add debug mode to the client

- CHANGES.md
- hcloud/certificate.go
- hcloud/certificate_test.go
- hcloud/datacenter.go
- hcloud/datacenter_test.go
- hcloud/floating_ip.go
- hcloud/floating_ip_test.go
- hcloud/image.go
- hcloud/image_test.go
- hcloud/iso.go
- hcloud/iso_test.go
- hcloud/load_balancer.go
- hcloud/load_balancer_test.go
- hcloud/load_balancer_type.go
- hcloud/load_balancer_type_test.go
- hcloud/location.go
- hcloud/location_test.go
- hcloud/network.go
- hcloud/network_test.go
- hcloud/server.go
- hcloud/server_test.go
- hcloud/server_type.go
- hcloud/server_type_test.go
- hcloud/ssh_key.go
- hcloud/ssh_key_test.go
- hcloud/volume.go
- hcloud/volume_test.go
In CertificateListOpts, Name is a string, thus we cannot differentiate
between Name unset and Name set to empty string. Making it a *string
would be a breaking change. So the only thing we can do is to
explicitly catch empty name in all those GetByName() methods.
Fixes #136.
> Make GetByName() return nil for empty names

- hcloud/client.go
httputil.DumpRequest was used before, which should only be used by
servers. Clients should use httputil.DumpRequestOut, which may produce
subtly different (and more accurate) output.
> DumpRequestOut is like DumpRequest but for outgoing client requests. It includes any headers that the standard http.Transport adds, such as User-Agent.
-- https://golang.org/pkg/net/http/httputil/#DumpRequestOut
I don't think it's worth mentioning this in the changelog. If you disagree let me know and I'll update it.
> use DumpRequestOut for debugging

- CHANGES.md
- hcloud/client.go
- hcloud/client_test.go
When using `hcloud.WithDebugWriter`, we currently output full HTTP requests and responses, including the `Authorization` header.
As we sometimes have to ask customers to provide debug logs, it's not ideal if they need to manually remove the header and may do so incompletely.
Redact the header in the output.
> HTTP debug logs: Redact Authorization header

- hcloud/image.go
- hcloud/schema.go
- hcloud/schema/firewall.go
- hcloud/schema/image.go
- hcloud/schema_test.go
> Add deleted property to image

- hcloud/metadata/client.go
- hcloud/metadata/client_test.go
Fixes two issues:
1. Metadata client does not recognise unsuccessful HTTP response codes
2. Closed a potential memory leak (not closed HTTP response)
> Fix metadata client error detection

- hcloud/schema.go
Setting `UsePrivateIP` for targets when creating a LoadBalancer should be allowed, same as when creating the targets separately:
https://github.com/hetznercloud/hcloud-go/blob/cf8f35d1f96cc8d74d1706f9e834ed25a851300f/hcloud/load_balancer.go#L567-L573
https://github.com/hetznercloud/hcloud-go/blob/cf8f35d1f96cc8d74d1706f9e834ed25a851300f/hcloud/load_balancer.go#L597-L603
> Set UsePrivateIP for targets when creating a LoadBalancer

- go.mod
- go.sum
- hcloud/client.go
- hcloud/client_test.go
This PR handles tokens that have been previously for example encoded in base64 for Kubernetes in an erroneous way containing newline characters.
Currently the error returned return the token value. This may be an unexpected value exposure not intended by an operator.
Example:
`net/http: invalid header field value "Bearer broken\n" for key Authorization`
Applying this change changes the error to not contain any sensitive data anymore:
`Authorization token contains invalid characters`
> Catch invalid token values and error out without value exposure

- .gitlab-ci.yml
- hcloud/client.go
- hcloud/hcloud.go
- hcloud/pricing.go
- hcloud/primary_ip.go
- hcloud/primary_ip_test.go
- hcloud/schema.go
- hcloud/schema/pricing.go
- hcloud/schema/primary_ip.go
- hcloud/schema/server.go
- hcloud/schema_test.go
- hcloud/server.go
- hcloud/server_test.go
> Add Primary IP Support

- hcloud/action_test.go
- hcloud/client.go
- hcloud/client_test.go
It does not make sense to retry when the rate limit is already exceeded. However, it makes sense to retry on Conflict. In the best case this would happen on the Caller/User side, but removing the retry completely would be a breaking change.
> Stop automatic retrying on RateLimitExceeded

- hcloud/primary_ip.go
This was missed when implementing the primary ip client.
> PrimaryIPClient Add AllWithOpts

- hcloud/primary_ip.go
- hcloud/primary_ip_test.go
- hcloud/schema/primary_ip.go
The API returns a CIDR range in the `ip` field for ipv6 primary IPs. This caused the `PrimaryIPClient.Update` call to fail, because the response was parsed as a `net.IP`, but should have been parsed using `net.ParseNetwork`.
The required logic was already implemented in the `PrimaryIPFromSchema` function, but not used for the update call.
With this commit, the struct `hcloud.PrimaryIPUpdateResult` is removed, because using it to parse the response causes the error and it was never returned from any of our methods, so consumers should not be using it.
This error was originally found in hcloud-cli, and caused following error message:
➜  ~ hcloud primary-ip update --auto-delete=false test-ip
hcloud: updating Primary IP test-ip failed: invalid IP address: 2001:db8::/64
> fix: error when updating IPv6 Primary IP

- .github/workflows/ci.yml
- README.md
We require Go 1.18 according to `go.mod`, but still test against 1.17.
This removes the testing and codifies our supported Go versions.
> ci: test against actually supported Go versions

- hcloud/pricing.go
- hcloud/schema.go
- hcloud/schema/pricing.go
- hcloud/schema_test.go
The /pricing API endpoint for primary IPs does not return individual DCs anymore but just regions ("fsn1", "nbg1", ...). I have changed the key name in the schema and updated the test for the new format.
> Fix schema for primary IP pricing to reflect the current API response

- hcloud/action.go
- hcloud/action_test.go
- hcloud/client.go
- hcloud/client_test.go
Using a configurable backoff algorithm to wait for actions allows users to fine tune api-requests versus latency of updates.
Using a longer, potentially exponential backoff allows the user to use less API requests in non-interactive contexts, where they only care about the result of the action, and not progress updates.
Closes #221
> feat(action): use configurable backoff to wait for action progress

- .github/CODEOWNERS
- .gitlab/CODEOWNERS
Add CODEOWNERS files for GitHub and (internal) GitLab referencing the Integrations team.
> chore: add codeowners

- .github/workflows/ci.yml
- .github/workflows/golangci-lint.yml
These actions were causing deprecation warnings as they were using Node 12.
> ci: update actions

- hcloud/schema/server.go
- hcloud/server.go
- hcloud/server_test.go
The existing method `ServerClient.Rebuild` did not return the root password and there was no way to add it without breaking API compatibility.
Closes #244
> feat: add ServerClient.RebuildWithResult to return root password

- hcloud/certificate.go
- hcloud/schema.go
- hcloud/schema/server_type.go
- hcloud/server_type.go
Field was recently added to the API: https://docs.hetzner.cloud/#server-types
> feat(servertype): add field for included traffic

- hcloud/schema/server_type.go
- hcloud/server_type.go
This is theoretically a breaking change, but the version that introduced the type was released 20 minutes ago.
Failed here while trying to build the clie preview: https://github.com/hetznercloud/cli/actions/runs/4947310060
> fix(servertype): use int64 to fit TB sizes on 32-bit platforms

- hcloud/action.go
- hcloud/certificate.go
- hcloud/firewall.go
- hcloud/floating_ip.go
- hcloud/load_balancer.go
This PR simplifies some client implementations of `.All` by calling `.AllWithOpts` with the according default options.
Fixes #257
> refactor: re-use implementation of `.AllWithOpts` for `.All`

- hcloud/datacenter.go
- hcloud/datacenter_test.go
- hcloud/load_balancer_type.go
- hcloud/load_balancer_type_test.go
- hcloud/location.go
- hcloud/location_test.go
- hcloud/server_type.go
- hcloud/server_type_test.go
This PR adds an implementation of the `.AllWithOpts` method to following clients:
- `DatacenterClient`
- `LoadBalancerTypeClient`
- `LocationClient`
- `ServerTypeClient`
Fixes #256
> feat: provide `.AllWithOpts` method for all clients

- hcloud/deprecation.go
- hcloud/deprecation_test.go
- hcloud/load_balancer_test.go
- hcloud/rdns.go
- hcloud/schema.go
- hcloud/schema/deprecation.go
- hcloud/schema/server_type.go
- hcloud/schema_test.go
- hcloud/server_test.go
- hcloud/server_type.go
- hcloud/testing.go
We recently added a new field to the ServerType API response that indicates if and when the server type was deprecated. The same structure will also be used for other resources in the future, replacing the current `deprecated` fields.
Marked as draft until I have finished the implementation in our other Go Integrations, to make sure that this feels ergonomic.
> feat(servertype): implement new Deprecation api field

- hcloud/labels.go
- hcloud/labels_test.go
According to the api documentation, the length of a label value must be a string of 63 characters or fewer.
The currently used regex for the validation allows 64 char long values.
> fix: adjust label validation for max length of 63 characters

- renovate.json
- renovate.json5
Changelogs should contain user-relevant stuff, updating dependencies is mostly not. Full list of commits is also linked in the changelog.
> chore: do not include renovate PRs in changelog

- hcloud/network.go
- hcloud/network_test.go
- hcloud/schema.go
- hcloud/schema/network.go
Feature was released today.
Marked as draft until the other Go integrations are ready.
> feat(network): add field expose_routes_to_vswitch

- hcloud/action.go
The progress was updated incorrectly and only over showed `0` or `1/len(actions)`.
> fix(action): show accurate progress in WatchOverallProgress

- .gitlab-ci.yml
The CI pipeline is not running because of a missing tag.
I am moving the default GitLab pipeline config (job tags, job templates) to a shared repository.
> ci: fix gitlab pipeline not running

- hcloud/action.go
- hcloud/certificate.go
- hcloud/client.go
- hcloud/datacenter.go
- hcloud/firewall.go
- hcloud/floating_ip.go
- hcloud/image.go
- hcloud/iso.go
- hcloud/load_balancer.go
- hcloud/load_balancer_type.go
- hcloud/location.go
- hcloud/network.go
- hcloud/placement_group.go
- hcloud/primary_ip.go
- hcloud/server.go
- hcloud/server_type.go
- hcloud/ssh_key.go
- hcloud/volume.go
This allows me to reuse the listing options to implement my own listing API calls.
> feat: make the ListOpts.Values method public

- hcloud/internal/instrumentation/metrics.go
- hcloud/internal/instrumentation/metrics_test.go
> fix(instrumentation): multiple instrumented clients cause panic

- hcloud/metadata/client.go
Some users might try to access the metadata service even though their networking setup breaks connectivity. This might lead to forever stalled connections. By setting a timeout we can error out instead of waiting indefinitely.
In my tests the metadata service responded in 12-40ms, so a default timeout of 1 second should be enough to only fail when the metadata service is actually unavailable.
> feat(metadata): add timeout option

- hcloud/action.go
- hcloud/certificate.go
- hcloud/datacenter.go
- hcloud/firewall.go
- hcloud/floating_ip.go
- hcloud/iso.go
- hcloud/load_balancer.go
- hcloud/load_balancer_type.go
- hcloud/location.go
- hcloud/network.go
- hcloud/placement_group.go
- hcloud/primary_ip.go
- hcloud/server_type.go
The clients `.All()` & `.AllWithOpts()` methods returned an inconsistent slice value when no resources were found. Some clients returned a `nil` slice while others returned an empty slice with 0 entries.
This makes sure that all methods return empty slices except if an actual error occured.
> refactor: Return consistent empty slice from .All() methods

- hcloud/action.go
- hcloud/action_test.go
When passed an action with an unknown ID, the `ActionClient.WatchProgress()` and `ActionClient.WatchOverallProgress()` methods experience unexpected behaviour:
- `WatchProgress()` would panic with a nil pointer dereference when accessing `a.Status`
- `WatchOverallProgress()` would go into an infinite loop, never finishing or closing the channels.
> fix(action): unexpected behaviour when watching non-existing Actions

- hcloud/action.go
- hcloud/action_test.go
Include the running action progress in the actions progress calculation.
The function now considers a failed action as completed, and is included in the progress. Not counting the failed action as completed might send some weird progress values e.g. [0%, 75%, (failed action occurs here) 50%], while if we count them, we should have [0%, 75%, 100%].
Related to https://github.com/hetznercloud/cli/issues/528
> fix: include running action progress in WatchOverallProgress

- hcloud/action.go
- hcloud/action_test.go
Backport 867aa632521ad3acfb04beb52b6307330740fc68 from #304.
> [Backport release-1.x] fix: send more precise progress values (#304)

- hcloud/action.go
- hcloud/action_test.go
- hcloud/certificate.go
- hcloud/client.go
- hcloud/firewall.go
- hcloud/floating_ip.go
- hcloud/image.go
- hcloud/load_balancer.go
- hcloud/network.go
- hcloud/primary_ip.go
- hcloud/server.go
- hcloud/volume.go
Related to https://docs.hetzner.cloud/changelog#2023-06-29-resource-action-endpoints
The existing `ActionClient` has two purposes:
- Expose the `GET /v1/actions` & `GET /v1/actions/:id` endpoints
- Provider helper methods for waiting on running actions
The new resource-specific endpoints do not need the helper methods, so I have refactored the code for the endpoints into the `ResourceActionClient`. This client is exposed by all resources that have actions as `client.Server.Action`. In addition, I have replaced the implementation of the two endpoints in `ActionClient` by forwarding them to an instance of `ResourceActionClient`.
> feat: support resource-specific Action endpoints

- hcloud/action.go
- hcloud/action_test.go
- hcloud/certificate.go
- hcloud/client.go
- hcloud/firewall.go
- hcloud/floating_ip.go
- hcloud/image.go
- hcloud/load_balancer.go
- hcloud/network.go
- hcloud/primary_ip.go
- hcloud/server.go
- hcloud/volume.go
Related to https://docs.hetzner.cloud/changelog#2023-06-29-resource-action-endpoints
The existing ActionClient has two purposes:
- Expose the GET /v1/actions & GET /v1/actions/:id endpoints
- Provider helper methods for waiting on running actions
The new resource-specific endpoints do not need the helper methods, so I have refactored the code for the endpoints into the ResourceActionClient. This client is exposed by all resources that have actions as client.Server.Action. In addition, I have replaced the implementation of the two endpoints in ActionClient by forwarding them to an instance of ResourceActionClient.
(cherry picked from commit ddc2ac45489c48a7563806c425222236ab1f8aa0 #295)
> feat: support resource-specific Action endpoints (#295)

- hcloud/client.go
We assign the custom poll back off function to the wrong variable `backoffFunc`, it should be stored in `pollBackoffFunc`.
https://github.com/hetznercloud/hcloud-go/blob/d6505ac13d68be8d52e9bfd8a483f68cf821a2f4/hcloud/client.go#L62
Related to https://github.com/hetznercloud/terraform-provider-hcloud/issues/761
> fix: ensure the pollBackoffFunc is correctly assigned

- hcloud/iso.go
- hcloud/iso_test.go
- hcloud/schema.go
- hcloud/schema/iso.go
See these changelog entries for the announcement:
- https://docs.hetzner.cloud/changelog#2023-10-12-deprecation-info-for-isos
- https://docs.hetzner.cloud/changelog#2023-10-12-field-deprecated-on-isos-is-now-deprecated
The removed function `func (iso *ISO) IsDeprecated() bool` will still be available, but through the `DeprecatableResource` embbeded struct. User code will still work as before, but use the new data source instead.
> feat(iso): support deprecation info API

- hcloud/client.go
- hcloud/client_test.go
- hcloud/error.go
This allows us to show more useful information in debug logs in downstream projects.
> feat(error): include http response in api errors

- hcloud/datacenter.go
- hcloud/load_balancer_type.go
- hcloud/schema/datacenter.go
- hcloud/schema/load_balancer_type.go
- hcloud/schema/server.go
- hcloud/schema_gen.go
- hcloud/server.go
- hcloud/zz_schema.go
Multiple properties were missing, even though they are documented in the API docs.
This PR needs https://github.com/hetznercloud/hcloud-go/pull/343 to be merged first.
Continuation of #347
> feat: add missing properties

- hcloud/schema/image.go
- hcloud/schema/iso.go
- hcloud/schema/server_type.go
- hcloud/schema_gen.go
- hcloud/zz_schema.go
In some places the schema definitions are not consistent with the API documentation, for example properties may not have pointer receivers even though they are marked as optional in the documentation. This results in inconsistent JSON when converting `JSON -> Schema -> JSON` (as seen for example in https://github.com/hetznercloud/cli/issues/461, where one output is the exact API response and one is serialized and then converted back to JSON).
This PR aims to fix this issue by making the schema definitions consistent.
> fix: make schemas consistent with API

- .golangci.yaml
> ci: forbid the use of fmt.Print methods using linter

- hcloud/schema/iso.go
- hcloud/schema_gen.go
- hcloud/schema_test.go
- hcloud/zz_schema.go
Try to mitigate the removal of the deprecated field from the API, by linking the `deprecated` field value to the deprecation info object.
> feat: alias deprecated field to deprecation info struct

- hcloud/schema_test.go
> test: ensure the deprecated field is aliased to the deprecation info

- hcloud/error.go
- hcloud/error_test.go
`hcloud.IsError()` currently does a type assertion to get our error type. This breaks if the error was previously wrapped, causing it to always return "false". This happens often if the error is passed through multiple functions before error handling is being done.
Example of code that is currently broken:
```go
// Error returned by hcloud-go
err := hcloud.Error{ Code: hcloud.ErrorCodeUnauthorized }
// Error gets wrapped at some point in the call-chain
err = fmt.Errorf("failed to foobar: %w", err)
// Now the error is not properly identified
hcloud.IsError(err, hcloud.ErrorCodeUnauthorized) // false
```
> feat(error): handle wrapped errors in IsError()

- hcloud/server.go
The `linux32` type is no longer allowed when enabling rescue mode ([See docs](https://docs.hetzner.cloud/changelog#2024-01-08-server-action-enable-rescue-no-longer-supports-32bit))
> feat(server): deprecate ServerRescueTypeLinux32

- .github/workflows/ci.yml
- go.mod
This follows our Go version policy https://github.com/hetznercloud/hcloud-go#go-version-support, but we don't want to force an unjustified go version upgrade for users of this library, so we only require go 1.20 instead of go 1.21.
The prometheus client_golang bumped the required go version to 1.20, we need to follow to be able to upgrade this dependency: https://github.com/hetznercloud/hcloud-go/pull/388
> feat: require Go >= 1.20

- hcloud/schema_gen.go
- hcloud/schema_test.go
- hcloud/zz_schema.go
In the conversion from LoadBalancerUpdateServiceOpts to schema.LoadBalancerActionUpdateServiceRequest, there are conversions from slices to slice pointers. Slice pointers exist in schemas to differentiate between absent and empty.
Goverter converts nil slices to &nil. This leads to the field being marshaled to `null` in JSON (even with the `omitempty` flag) instead of being not present (See https://github.com/hetznercloud/cli/issues/702)
This PR fixes this issue by adding manual conversion methods and adds tests to account for this behavior.
> fix: LoadBalancerUpdateServiceOpts not converted correctly

- .github/workflows/ci.yml
- .gitlab-ci.yml
Add go 1.22 to the test matrix.
> feat: test with Go 1.22

- hcloud/schema/volume.go
- hcloud/schema_test.go
- hcloud/volume.go
- hcloud/zz_schema.go
This property was previously missing, although it was already used in VolumeCreateOpts. It's now a string pointer with common values (ext4 and xfs) available as string constants.
> feat: add volume format property

- README.md
This makes it easy to install the correct dependency, as it deviates from our GitHub URL (`github.com/hetznercloud/hcloud-go` vs `github.com/hetznercloud/hcloud-go/v2/hcloud`)
> docs: installation command in readme

- hcloud/client.go
Add documentation for the v attribute in `Client.Do()` as it behaves very differently depending on the provided type.
> docs: Document possible types for the v attribute of Client.Do()

- hcloud/action_test.go
- hcloud/client.go
- hcloud/error.go
- hcloud/error_test.go
This commit changes the way error responses from the API are formatted for display to users. When available, it adds the Correlation (Trace) ID header to the error string.
We often have users that post the error string, but rarely do users have debug logging active. By adding the correlation ID to error messages, we can more quickly investigate why something went wrong using the Hetzner internal tracing system.
This is common practice in Web Apps, they usually show a request/trace ID or an encrypted blob in case of an internal server error.
> feat(error): show internal correlation id in error messages

- .github/workflows/backport.yml
The previous templates were not compatible with our usage:
- The title was prefixed with `[Backport release-1.x]` which broke `release-please`
- The body was empty besides the comment about backporting. By default we use the PR body as the commit message, so we should include the relevant details here.
> ci: improve backport PR title and body

- .github/workflows/ci.yml
- go.mod
- go.sum
This is required for us to use the `maps` stdlib.
> feat: require Go >= 1.21

- .golangci.yaml
```
$ golangci-lint run --fix                
WARN [config_reader] The configuration option `linters.errcheck.exclude` is deprecated, please use `linters.errcheck.exclude-functions`. 
```
> chore: remove unused and deprecated lint config

- hcloud/action_waiter.go
- hcloud/action_waiter_test.go
- hcloud/action_watch.go
- hcloud/action_watch_test.go
- hcloud/client_test.go
- hcloud/interface_gen.go
- hcloud/mocked_test.go
- hcloud/zz_action_client_iface.go
Implement a simpler and more versatile waiting functions for actions.
Most use cases when waiting for actions is to return early if an action fails. If all actions must be waited until completion, the users should use the `WaitForFunc` function.
If the final actions objects are needed, the users should use the `WaitForFunc` function to store the final actions using the `handleUpdate` callback.
This deprecates the `ActionClient.WatchOverallProgress`  and `ActionClient.WatchProgress` methods.
> feat: implement actions waiter

- hcloud/action_waiter.go
- hcloud/zz_action_client_iface.go
Link was not working properly in current `main`: https://pkg.go.dev/github.com/hetznercloud/hcloud-go/v2/hcloud@v2.7.3-0.20240503164107-1e3fa7033d8a#ActionClient.WaitFor
> docs(action): fix link to WaitForFunc

- hcloud/error.go
- hcloud/error_test.go
This improves the format of our error message, as they might be printed to the users.
Before:
```
hcloud: server name is already used (uniqueness_error) (Correlation ID: d5064a1f0bb9de4b)
```
After:
```
hcloud: server name is already used (uniqueness_error, d5064a1f0bb9de4b)
```
> fix: improve error message format with correlation id

- hcloud/action_waiter.go
- hcloud/action_waiter_test.go
- hcloud/action_watch.go
- hcloud/action_watch_test.go
- hcloud/client_test.go
- hcloud/mocked_test.go
Implement a simpler and more versatile waiting functions for actions.
Most use cases when waiting for actions is to return early if an action fails. If all actions must be waited until completion, the users should use the `WaitForFunc` function.
If the final actions objects are needed, the users should use the `WaitForFunc` function to store the final actions using the `handleUpdate` callback.
This deprecates the `ActionClient.WatchOverallProgress` and `ActionClient.WatchProgress` methods.
(cherry picked from commit 1e3fa7033d8a1cea1c0a9007a6255798979f0771)
feat: implement actions waiter
> feat: implement actions waiter (#407) [Backport release-1.x]

- hcloud/action_waiter.go
Link was not working properly in current `main`:
https://pkg.go.dev/github.com/hetznercloud/hcloud-go/v2/hcloud@v2.7.3-0.20240503164107-1e3fa7033d8a#ActionClient.WaitFor
(cherry picked from commit 94229eba296bbb03727eec7a028276a14db33431)
docs(action): fix link to WaitForFunc
> docs(action): fix link to WaitForFunc (#429) [Backport release-1.x]

- hcloud/schema.go
- hcloud/schema/volume.go
- hcloud/schema_test.go
- hcloud/volume.go
This property was previously missing, although it was already used in VolumeCreateOpts. It's now a string pointer with common values (ext4 and xfs) available as string constants.
(cherry picked from commit c0940afce9eb01c0e6838502c91aa569ab411a03)
feat: add volume format property
> feat: add volume format property (#397) [Backport release-1.x]

- go.mod
- go.sum
- hcloud/exp/kit/ssh/ssh_key.go
- hcloud/exp/kit/ssh/ssh_key_test.go
This adds a few ssh key utilities in the ssh kit package. The functions are used in multiple Hetzner Cloud projects.
> feat(exp): add ssh key functions

- hcloud/exp/kit/sshutils/ssh_key.go
- hcloud/exp/kit/sshutils/ssh_key_test.go
The package url and name were different. Use the `sshutils` package name to prevent collision with the stdlib ssh package.
> fix(exp): rename to `sshutils` package name

- hcloud/exp/actionutils/actions.go
- hcloud/exp/actionutils/actions_test.go
Use a smaller name, as we already refer to actions in the package name: 
- `actionutils.AppendNextActions ` => `actionutils.AppendNext`
> feat(exp): rename `AppendNextActions` to `AppendNext`

- hcloud/schema_test.go
- hcloud/server_type_test.go
Learn more: https://docs.hetzner.cloud/changelog#2024-06-06-old-server-types-with-shared-intel-vcpus-are-deprecated
> chore: replace deprecated server type with cx22

- hcloud/exp/README.md
Both namespace have different purposes, this was not documented.
> docs: document difference between the `exp` and `exp/kit` namespaces

- hcloud/action_waiter_test.go
- hcloud/mocked_test.go
Removes the now duplicated mock request utils, and uses the one introduced in #460.
> refactor: reuse mockutils package

- hcloud/client.go
- hcloud/client_handler.go
- hcloud/client_handler_debug.go
- hcloud/client_handler_debug_test.go
- hcloud/client_handler_error.go
- hcloud/client_handler_error_test.go
- hcloud/client_handler_http.go
- hcloud/client_handler_http_test.go
- hcloud/client_handler_parse.go
- hcloud/client_handler_parse_test.go
- hcloud/client_handler_rate_limit.go
- hcloud/client_handler_rate_limit_test.go
- hcloud/client_handler_retry.go
- hcloud/client_handler_retry_test.go
- hcloud/client_handler_test.go
This explodes the multiple concerns mixed in the `Do` method into multiple handlers that are chained, similar to the `http.RoundTripper`.
> refactor: explode Client.Do method into a chain of handlers 

- hcloud/exp/labelutils/selector.go
- hcloud/exp/labelutils/selector_test.go
This method is very helpful if you want to create resources and later clean them up with the same label set. Creating resources requires a `map[string]string`, but filtering resource lists takes a selector string.
> feat(exp): add labelutils with selector

- hcloud/action_waiter.go
Filter out nil actions, to help users of the function.
Backport commit 4fc9a4039d45071124a435121642ca396a8237c0 into release-1.x
> feat: filter out nil actions in action waiter (#464)

- hcloud/exp/mockutils/mockutils.go
- hcloud/exp/mockutils/mockutils_test.go
Ensure the headers are configured before we set the status code and send the headers.
> fix(exp): configure response headers before sending them

- hcloud/exp/mockutils/mockutils.go
- hcloud/exp/mockutils/mockutils_test.go
If the `Request.Path` value is not set, this allows the path matching to happen in the `Request.Want` function.
We sometimes have random values in the URL that require more advanced paths matching.
> fix(exp): allow request path matching in the want function

- hcloud/client.go
- hcloud/client_test.go
- Add a truncated exponential back off function with full jitter,
- The existing exponential back off function is now capped to 60s.
https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/
> feat: add truncated exponential backoff with full jitter backoff

- hcloud/action_waiter_test.go
- hcloud/client.go
- hcloud/client_handler.go
- hcloud/client_handler_error.go
- hcloud/client_handler_retry.go
- hcloud/client_handler_retry_test.go
- hcloud/hcloud.go
Closes #311
Implement a retry handler to retry requests based on an internal retry policy.
The retry policy will evolve over time to cover more use cases, but for now we want to start simple, and maybe someday allow users to tweak the retry policy.
feat: retry requests when the api is unavailable (#470)
feat: retry requests when the rate limit was reached (#470)
feat: retry requests when the network timed out (#470)
feat: respect cancelled contexts during retry sleep (#470)
> feat: implement retry mechanism

- hcloud/action_waiter_test.go
- hcloud/exp/README.md
- hcloud/exp/actionutil/actions.go
- hcloud/exp/actionutil/actions_test.go
- hcloud/exp/kit/envutil/env.go
- hcloud/exp/kit/envutil/env_test.go
- hcloud/exp/kit/sshutil/ssh_key.go
- hcloud/exp/kit/sshutil/ssh_key_test.go
- hcloud/exp/labelutil/selector.go
- hcloud/exp/labelutil/selector_test.go
- hcloud/exp/mockutil/http.go
- hcloud/exp/mockutil/http_test.go
- hcloud/mocked_test.go
Use a smaller and clearer package name.
>  feat(exp): rename `*utils` package to `*util`

- hcloud/action_waiter_test.go
- hcloud/client_handler_retry.go
- hcloud/client_handler_retry_test.go
- hcloud/hcloud.go
Related to #470
This is only a `chore` to prevent confusion with the now updated release-please commits in #470  
We prefer not to retry requests:
- If the ingress returns a "bare" 429, as the backend was not able to respond anyway.
- If the ingress returns a "bare" 503, to prevent possible self-made DDoS, and preventing a disaster recovery.
> chore: do not retry on bare HTTP 429 or HTTP 503

- hcloud/exp/kit/sliceutil/slice.go
- hcloud/exp/kit/sliceutil/slice_test.go
- Adds a Batches utility to split slices into batches.
> feat(exp): add sliceutil package

- hcloud/client.go
- hcloud/client_test.go
This lets the user configure the retry options, with a custom back off function and the max number of retries.
> feat: allow configuring retry options

- hcloud/exp/kit/sliceutil/slice.go
- hcloud/exp/kit/sliceutil/slice_test.go
Inspired by the new golang 1.23 Chunk implementation: https://togithub.com/golang/go/issues/53987
> fix(exp): set capacity for each batch

- hcloud/client.go
- hcloud/hcloud.go
Enable jitter in the client default retry exponential backoff function.
> feat: add jitter in the client default retry exponential backoff

- hcloud/error.go
- hcloud/error_test.go
Useful when one need to check multiple error codes at once, without having to cast every time.
```diff
-hcloud.IsError(err, hcloud.ErrorCodeConflict) || hcloud.IsError(err, hcloud.ErrorCodeLocked)
+hcloud.IsError(err, hcloud.ErrorCodeConflict, hcloud.ErrorCodeLocked)
```
> feat: allow checking multiple errors codes in `IsError`

- hcloud/action_waiter.go
- hcloud/action_watch.go
- hcloud/client.go
- hcloud/client_test.go
- hcloud/zz_action_client_iface.go
- Improve consistency with the pattern used with `WithRetryOpts`,
- Use the `PollOpts` struct, which is more future-proof than function arguments (properties can be added without breaking),
- Update docs to use the latest `WithPollOpts` instead of the deprecated alternative.
Since we already changed the way to configure the retry options, I think it is a good time to also change the pattern for the poll opts, even if this does not really bring a new feature.
> feat: add new `WithPollOpts` client option

- hcloud/pricing.go
- hcloud/schema/pricing.go
- hcloud/schema/server_type.go
- hcloud/schema_gen.go
- hcloud/server_type.go
- hcloud/zz_schema.go
The API has been updated to provide a better insight and more flexibility for displaying the pricing of traffic for servers and load balancers.
In addition to the new fields, the old fields are deprecated and will be set to `null` in the API on 2024-08-05.
As far as we could tell they are not widely used in Open Source code, please check if you are using them in any private code. Some linters automatically check for deprecated fields, if you use `golangci-lint` this is provided by the `staticcheck` linter.
You can learn more about this change in [our changelog](https://docs.hetzner.cloud/changelog#2024-07-25-cloud-api-returns-traffic-information-in-different-format).
If you were using the field `hcloud.ServerType.IncludedTraffic`, you can now get the information through …
> feat: new APIs for traffic pricings

- hcloud/pricing.go
- hcloud/schema.go
- hcloud/schema/pricing.go
- hcloud/schema/server_type.go
- hcloud/schema_test.go
- hcloud/server_type.go
The API has been updated to provide a better insight and more flexibility for displaying the pricing of traffic for servers and load balancers.
In addition to the new fields, the old fields are deprecated and will be set to `null` in the API on 2024-08-05.
As far as we could tell they are not widely used in Open Source code, please check if you are using them in any private code. Some linters automatically check for deprecated fields, if you use `golangci-lint` this is provided by the `staticcheck` linter.
You can learn more about this change in [our changelog](https://docs.hetzner.cloud/changelog#2024-07-25-cloud-api-returns-traffic-information-in-different-format).
If you were using the field `hcloud.ServerType.IncludedTraffic`, you can now get the information through …
> feat: new APIs for traffic pricings [release-1.x]

- hcloud/network.go
- Update the properties documentation
- Add deprecation warning for long deprecated `NetworkSubnetTypeServer`.
> fix: update `NetworkSubnetType` constants

- hcloud/network.go
Network Zone was added today and includes the `sin` (Singapore) location.
Learn more at https://docs.hetzner.cloud/changelog#2024-08-06-new-location-singapore
> feat(network): add new network zone ap-southeast

- hcloud/network.go
Network Zone was added today and includes the `sin` (Singapore) location.
Learn more at https://docs.hetzner.cloud/changelog#2024-08-06-new-location-singapore
> feat(network): add new network zone ap-southeast [release-1.x]

- hcloud/schema/error.go
The create uploaded certificate endpoint may return the following error:
```
{
"error": {
"code": "invalid_input",
"message": "certificate must use larger key size"
}
}
```
This change ensure that we do not get a json unmarshal error (unexpected end of json) while trying to parse a non-existing details data.
> fix: `invalid_input` API errors may not return details

- hcloud/pricing.go
- hcloud/schema/pricing.go
- hcloud/schema_gen.go
See https://docs.hetzner.cloud/changelog#2024-08-29-field-floating_ip-in-pricing-response-is-now-deprecated
> fix: deprecate pricing floating ip field

- hcloud/action.go
When an action error occurs within the action waiter utilities, we are missing information about the related action that failed. With this change, we can now retrieve the action that triggered the failure after casting the error to an action error.
> feat: allow retrieving the action from an action error

- hcloud/action.go
- hcloud/action_test.go
This allows us to easily debug the failed action from user provided logs.
> feat: include action ID in action error string

- hcloud/exp/mockutil/http.go
Ensure test failure when some call were expected, but were not received.
e.g. we have a single mocked request, but the test does not generate any call, the test should fail.
> feat(exp): fail test when mock calls were expected but not received

- hcloud/exp/mockutil/http.go
- hcloud/exp/mockutil/http_test.go
This helper ensures that the wrapped test server will be closed at the end of each test.
> feat(exp): add mockutil.Server helper

- hcloud/load_balancer.go
- hcloud/load_balancer_test.go
- hcloud/schema/id_or_name.go
- hcloud/schema/id_or_name_test.go
- hcloud/schema/load_balancer.go
- hcloud/schema/server.go
- hcloud/schema/volume.go
- hcloud/schema_gen.go
- hcloud/schema_test.go
- hcloud/server.go
- hcloud/server_test.go
- hcloud/volume.go
- hcloud/volume_test.go
- hcloud/zz_schema.go
Add typing information to the fields that support passing either an ID as int, an ID as string or a Name as string. An empty value will be marshalled to `null` to reflect the behavior of an empty interface.
After this change, we do not have to cast IDs to float64 or to string to be able to read the values.  
Since this is part of the schema package, this is not a breaking change for our customers, but might break our tests that rely on casting the interface to the desired type.
> feat: use custom IDOrName type for schemas

- hcloud/metadata/client.go
- hcloud/metadata/client_test.go
> fix(metadata): trim responses before parsing

- hcloud/primary_ip.go
- hcloud/primary_ip_test.go
The ID is not part of the request body docs, but was still send. This removes the ID from the request body.
> fix: do not send primary IPs ID opts to the API

- hcloud/primary_ip.go
- hcloud/primary_ip_test.go
The ID is not part of the request body docs, but was still send. This removes the ID from the request body.
> fix: do not send primary IPs ID opts to the API (#552)

- hcloud/exp/mockutil/http.go
- hcloud/exp/mockutil/http_test.go
This allows to extend the list of requests the server expects to respond to.
This also REPLACES the `mockutil.Server` function with a struct. You can create a new Server using the `mockutil.NewServer` function.
> feat(exp): add mock requests after mock server creation

- hcloud/network.go
- hcloud/schema/network.go
- hcloud/zz_schema.go
Fixes #567
See https://docs.hetzner.cloud/#networks-get-a-network
> fix: missing load-balancers property in network schema

- hcloud/exp/kit/randutil/id.go
- hcloud/exp/kit/randutil/id_test.go
Handy helper used in multiple of our projects.
> feat(exp): add `randutil.GenerateID` helper

- hcloud/error.go
- hcloud/schema/error.go
- hcloud/schema/error_test.go
- hcloud/schema_gen.go
- hcloud/schema_test.go
This error code is returned when a user tries to access functionality that was removed from the API. It contains a link to the changelog announcement describing the removal.
> feat: add deprecated_api_endpoint error code

- hcloud/action.go
- hcloud/zz_action_client_iface.go
On 30 January 2025 we removed the functionality to get all actions from `GET /v1/actions`. The endpoint now requires the `?id=` parameter and returns a `deprecated_api_endpoint` response otherwise.
This deprecation was announced in July 2023.
Changelog: https://docs.hetzner.cloud/changelog#2025-01-30-listing-arbitrary-actions-in-the-actions-list-endpoint-is-removed
> feat: update ActionClient for actions list removal

- README.md
- hcloud/hcloud.go
Users must subscribe to our changelog, or they might not be notified about additions, deprecations and removals.
> docs: add links to api changelog

- hcloud/client.go
Ensure the back off function is not nil when a user only configures the `RetryOpts.MaxRetries` value.
Fixes to #586
> fix: ignore nil backoff function when configuring poll or retry options

- .github/workflows/ci.yml
- .github/workflows/release-please.yml
- MAINTAINERS.md
- README.md
Related to #263
This removes support for our v1 maintenance releases branch.
> docs: drop support for the v1 releases

- .github/workflows/ci.yml
- .github/workflows/release-please.yml
- MAINTAINERS.md
- README.md
Related to #263
This removes support for our v1 maintenance releases branch.
(cherry picked from commit 54f73407625c693ee619d2ee15018e3da91e5187)
> docs: drop support for the v1 releases (#590)

- hcloud/action_waiter.go
The `/actions?id=` endpoint should only be request at most 25 actions at once, or the extra actions might not be returned at all.
> fix: request in batches of 25 when waiting for actions

- hcloud/action.go
- hcloud/certificate.go
- hcloud/datacenter.go
- hcloud/firewall.go
- hcloud/floating_ip.go
- hcloud/image.go
- hcloud/iso.go
- hcloud/load_balancer.go
- hcloud/load_balancer_type.go
- hcloud/location.go
- hcloud/network.go
- hcloud/placement_group.go
- hcloud/pricing.go
- hcloud/primary_ip.go
- hcloud/server.go
- hcloud/server_type.go
- hcloud/ssh_key.go
- hcloud/volume.go
Consistently return the base response object even when errors occur.
Unless the return statement is before the `Do` function, all returns should include the response object.
> fix: missing response from requests return values

- hcloud/client_generic.go
- hcloud/client_generic_test.go
Those improvements were made after implementing the generics requests in the client.
- Allow passing nil request bodies
- Reduce nil checks on the caller side
> refactor: improve client generic requests

- hcloud/action.go
- hcloud/certificate.go
- hcloud/datacenter.go
- hcloud/firewall.go
- hcloud/floating_ip.go
- hcloud/image.go
- hcloud/iso.go
- hcloud/load_balancer.go
- hcloud/load_balancer_type.go
- hcloud/location.go
- hcloud/network.go
- hcloud/placement_group.go
- hcloud/primary_ip.go
- hcloud/server.go
- hcloud/server_type.go
- hcloud/ssh_key.go
- hcloud/volume.go
Uses the new generic requests function to reduce the code duplication for the `GetByID` calls.
> refactor: use generic request for all `GetByID` calls

- hcloud/action.go
- hcloud/certificate.go
- hcloud/client_helper.go
- hcloud/datacenter.go
- hcloud/firewall.go
- hcloud/floating_ip.go
- hcloud/image.go
- hcloud/iso.go
- hcloud/load_balancer.go
- hcloud/load_balancer_type.go
- hcloud/location.go
- hcloud/network.go
- hcloud/placement_group.go
- hcloud/primary_ip.go
- hcloud/server.go
- hcloud/server_type.go
- hcloud/ssh_key.go
- hcloud/volume.go
Uses the new generic requests function to reduce the code duplication for the `List` calls.
> refactor: use generic request for all `List` calls

- hcloud/certificate.go
- hcloud/client_helper.go
- hcloud/datacenter.go
- hcloud/firewall.go
- hcloud/floating_ip.go
- hcloud/image.go
- hcloud/iso.go
- hcloud/load_balancer.go
- hcloud/load_balancer_type.go
- hcloud/location.go
- hcloud/network.go
- hcloud/placement_group.go
- hcloud/primary_ip.go
- hcloud/server.go
- hcloud/server_type.go
- hcloud/ssh_key.go
- hcloud/volume.go
Uses the new generic requests function to reduce the code duplication for the `GetByName` calls (and others similar functions).
> refactor: use generic request for `GetByName` calls

- .github/workflows/ci.yml
Missing changes from when we dropped support for go v1.22 in #602
feat: drop go v1.22 (#602) (#621)
> ci: remove go 1.22 from test matrix

- hcloud/certificate.go
- hcloud/client_helper.go
- hcloud/firewall.go
- hcloud/floating_ip.go
- hcloud/image.go
- hcloud/iso.go
- hcloud/load_balancer.go
- hcloud/network.go
- hcloud/placement_group.go
- hcloud/primary_ip.go
- hcloud/server.go
- hcloud/ssh_key.go
- hcloud/volume.go
Uses the new generic requests function to reduce the code duplication for the `Get` calls.
> refactor: use generic request for `Get` calls

- hcloud/load_balancer.go
- hcloud/load_balancer_test.go
- hcloud/pricing.go
- hcloud/server.go
- hcloud/server_test.go
- hcloud/zz_load_balancer_client_iface.go
- Also split the metrics query parameter building into a `Validate() error` and a `values() url.Values` functions.
> refactor: use generic request for remaining get calls

- hcloud/network.go
- hcloud/server.go
This does not include the fixes for the primary ip client, because those changes are more involved.
Related to the comments in #624
> refactor: use correct response schema

- hcloud/primary_ip.go
- hcloud/primary_ip_test.go
- hcloud/schema.go
- hcloud/schema/primary_ip.go
- hcloud/schema_gen.go
- hcloud/zz_primary_ip_client_iface.go
- hcloud/zz_schema.go
- Move the request and response schema to the schema package
- Rename structs to follow the struct naming conventions:
- in the schema package we hold `Request` and `Response` structs
- in the hcloud package we hold `Opts` and `Result` structs
- Fix some response schema being used in the wrong places
- Deprecate the `Result` structs present in the hcloud package (should never be used by users)
> fix: move primary ip client request/response structs to schema package

- hcloud/client_generic_test.go
- hcloud/client_test.go
- hcloud/exp/ctxutil/ctxutil.go
- hcloud/internal/instrumentation/metrics.go
- hcloud/internal/instrumentation/metrics_test.go
- hcloud/metadata/client.go
- hcloud/metadata/client_test.go
When an instrumented client (API or Metadata) made a request that did not explicitly specify the OpPath through `ctxutil.SetOpPath()` that instrumentation code caused a panic.
This is now handled by adding back a fallback if the explicit OpPath is not set. The fallback uses the same patterns to create the OpPath as our manual paths.
This only happened for the Metadata client and any custom clients/requests that users added besides the official endpoints implemented in hcloud-go.
Bug was introduced in #626, thanks to @lukasmetzner for finding and reporting.
Co-authored-by: Jonas Lammler <jonas.lammler@hetzner-cloud.de>
> fix: panic when a request did not set the OpPath for instrumentation

- .golangci.yaml
- hcloud/action_waiter_test.go
- hcloud/action_watch_test.go
- hcloud/client_handler_error.go
- hcloud/client_handler_parse_test.go
- hcloud/client_handler_retry_test.go
- hcloud/client_handler_test.go
- hcloud/client_test.go
- hcloud/exp/kit/sshutil/ssh_key_test.go
- hcloud/exp/mockutil/http.go
- hcloud/exp/mockutil/http_test.go
- hcloud/internal/instrumentation/metrics.go
- hcloud/metadata/client_test.go
- hcloud/primary_ip_test.go
- hcloud/schema/error.go
- hcloud/schema/id_or_name_test.go
- hcloud/schema_gen.go
- hcloud/schema_test.go
- hcloud/server.go
- Updates the golangci config to use presets to use more linters.
- Make golangci lint happy.
> test: use golangci config presets

- hcloud/schema/README.md
- hcloud/schema/doc.go
Since we introduce breaking changes in the schema package, we must make sure people do not expect stability from it. This adds a small note about the stability of the schema package.
> docs: add note about the schema package stability

- hcloud/primary_ip.go
Missing refactor from our past refactor patch series.
> refactor: use generic `firstBy` for `GetByIP`

- hcloud/certificate.go
- hcloud/certificate_test.go
- hcloud/error.go
- hcloud/error_test.go
- hcloud/firewall.go
- hcloud/firewall_test.go
- hcloud/floating_ip.go
- hcloud/load_balancer.go
- hcloud/load_balancer_test.go
- hcloud/network.go
- hcloud/network_test.go
- hcloud/placement_group.go
- hcloud/server.go
- hcloud/server_test.go
- hcloud/ssh_key.go
- hcloud/volume.go
A new error used to streamline missing arguments errors or invalid values during validation in our library.
Related to #556
> feat: consistent argument errors

- hcloud/client.go
- hcloud/internal/instrumentation/metrics.go
- hcloud/internal/instrumentation/metrics_test.go
- hcloud/metadata/client.go
Configuration that set a custom HTTP client transport would be ignored. For example in this snippet, the `otelhttp.NewTransport` would not come into effect.
```go
httpClient := &http.Client{
Transport: otelhttp.NewTransport(
http.DefaultTransport,
),
}
opts := []hcloud.ClientOption{
hcloud.WithInstrumentation(reg),
hcloud.WithHTTPClient(httpClient),
}
client := hcloud.NewClient(opts...)
```
> fix: http transport ignored when using instrumentation

- hcloud/schema/storage_box_type.go
- hcloud/storage_box_type.go
- hcloud/storage_box_type_test.go
`snapshot_limit` and `automatic_snapshot_limit` are both nullable. We implemented them as required.
> fix: storage box type snapshot limits are nullable

- hcloud/schema/server.go
- hcloud/server.go
- hcloud/server_test.go
Adds the parameter `ip_range` to `ServerAttachToNetwork`.
Introduced by: https://docs.hetzner.cloud/changelog#2025-09-11-attach-to-network-support-ip-range
Required to change the following implementation:
https://github.com/kubernetes/autoscaler/pull/8334
@lukasmetzner  I'm only mentioning you because we already talked about this :)
Change for loadbalancers will follow soon...
> feat: add new ip_range param to ServerAttachToNetwork

- hcloud/load_balancer.go
- hcloud/load_balancer_test.go
- hcloud/schema/load_balancer.go
This pr adds the “ip_range” parameter to “LoadBalancerAttachToNetwork”, quiet similar to the pr which implements this feature for "ServerAttachToNetwork" from tloesch. (https://github.com/hetznercloud/hcloud-go/pull/723)
Hetzner now implemented this feature in their API.
Introduced by: https://docs.hetzner.cloud/changelog#2025-09-11-attach-to-network-support-ip-range
> feat: add new ip_range param to LoadBalancerAttachToNetwork
